[package]
name = "darc-query"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
darc-index = { workspace = true }
darc-paths = { workspace = true }
darc-rollout = { workspace = true }
anyhow = { workspace = true }
glob = { workspace = true }
memchr = { workspace = true }
regex = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
darc-test-utils = { workspace = true }
